version: '3'

services:
  traefik:
    # The latest official supported Traefik docker image
    image: traefik:latest
    # Enables the Traefik Dashboard and tells Traefik to listen to docker
    #  -log.level=INFO # so we can see what Traefik is doing in the log files
    ports:
      # Exposes port 80 for incomming web requests
      - "80:80"
      - "443:443"
      # The Web UI port http://0.0.0.0:8080 (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      # Copies the Let's Encrypt certificate locally for ease of backing up
      - ~/github/certs:/ssl
       # Mounts the Traefik static configuration inside the Traefik container
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./data/configurations:/dynamic_config

# Add Error Page service
  error:
     image: guillaumebriday/traefik-custom-error-pages
     labels:
       - "traefik.enable=true"
       - "traefik.http.routers.error.rule=Host(`fedora.adal-vimba.ts.net`)"
       - "traefik.http.routers.error.service=error"
       - "traefik.http.services.error.loadbalancer.server.port=80"
       - "traefik.http.routers.error.entrypoints=web"

# Error Pages Middleware
       - "traefik.http.middlewares.test-errorpages.errors.status=400-599"
       - "traefik.http.middlewares.test-errorpages.errors.service=error"
       - "traefik.http.middlewares.test-errorpages.errors.query=/{status}.html"

# Add the catapp service
  catapp:
     image: mikesir87/cats:1.0
     
     labels:
       - "traefik.enable=true"
  # Routers
       - "traefik.http.routers.catapp.rule=Host(`fedora.adal-vimba.ts.net`)"
       - "traefik.http.routers.catapp.entrypoints=web"
       - "traefik.http.routers.catapp.middlewares=test-redirectscheme"
       - "traefik.http.routers.catapp-secure.rule=Host(`fedora.adal-vimba.ts.net`) && PathPrefix(`/cat`)"
       - "traefik.http.routers.catapp-secure.entrypoints=websecure"
       - "traefik.http.routers.catapp-secure.middlewares=test-auth,test-compress,test-errorpages,test-ratelimit"
  # Services
       - "traefik.http.services.catapp-secure.loadbalancer.server.port=5000"

  # Define middleware for cat-app
       - "traefik.http.middlewares.web-app1-strip-prefix.stripprefix.prefixes=/cat"
  # Apply middleware to router
       - "traefik.http.routers.catapp-secure.middlewares=web-app1-strip-prefix"


  # Middleware BasicAuth
       - "traefik.http.middlewares.test-auth.basicauth.users=allen:$$apr1$$GJtu.zF1$$imsHiAKGWG0VSrBhV81CP1"       
  # Compress Middleware
       - "traefik.http.middlewares.test-compress.compress=true"
  # Error Pages Middleware
       - "traefik.http.middlewares.test-errorpages.errors.status=400-599"
       - "traefik.http.middlewares.test-errorpages.errors.service=error"
       - "traefik.http.middlewares.test-errorpages.errors.query=/{status}.html"
  # Rate Limit Middleware
       - "traefik.http.middlewares.test-ratelimit.ratelimit.average=2"
  # Redirect Scheme HTTP -> HTTPS
       - "traefik.http.middlewares.test-redirectscheme.redirectscheme.scheme=https"
       - "traefik.http.middlewares.test-redirectscheme.redirectscheme.permanent=true"







